name: AdvancedRankup
main: AdvanceRankup\RankUp
version: 1.0.0
author: TheGamerz13
api: 3.0.0
load: POSTWORLD
softdepend: ["EconomyAPI", "PurePerms"]
permissions:
 rankup:
  default: true
 prestige: true
  children:
    rankup.rankup:
      default: true
      description: Allow ranking up
    prestige.prestige
       default: true
       description: all you to prestige when you have max rankup
    rankup.admin:
      default: op
      description: Manage RankUp and view statistics
    rankup.groups:
      default: false
      description: Do NOT set this. It is used for group managment.
